### ISSUE TITLE
Add a generic contextual for finding tools 

### ISSUE THREAD

**Issue by ldionmarcil** [BlackArch/blackarch-config-i3#2]
On the main DE on BA, right clicking the desktop shows a list of packages organized by categories. This is done through .desktop files parsing and it's absolutely great for finding new tools. I suggest using dmenu because it's light and I think we should stick with i3's mentality of getting work done using the keyboard. 

Obviously we would have to parse the .desktop files to feed dmenu with data. I suggest a python script for this. I will try to outline the software requirements for it this week and think of some kind of possible implementation. Perhaps there's already a lib out there that already does it. If anyone feels up to the implementation, let me know.

**Comment by bashM0nk3y** [comment]
Doesn't dmenu work off of $PATH?

Why don't you just use i3wm instead of what sounds like fluxbox?
