### ISSUE TITLE
Possible i3 config error..?

### ISSUE THREAD

**Issue by bashM0nk3y** [BlackArch/blackarch-config-i3#4]
I am getting errors from line numbers 132-138 of the i3/config file.
Almost looks as if my variables aren't expanding properly..? https://imgur.com/a/1wDqI40
I imported the `blackarch-linux-2018.06.01.ova` into virtualbox, fwiw. This could very well be my fault, and I apologize if this turns out to be the case.

Thanks!

**Comment by ikstream** [comment]
@bashM0nk3y I think its ok to leave it open until the pull request is merged, so others can see that the problem they encounter is already adressed

**Comment by PedroSFreitas** [comment]
@ikstream I don't see the merge. Are you sure?

**Comment by ikstream** [comment]
My bad! I saw no more open PRs in _this_ repo, checked, last pr was merged and assumed as fixed.

**Comment by PedroSFreitas** [comment]
@ikstream no problem. It happens.
I'm thinking about making changes on i3-config and close the x11-config PR. I'll think about it and see what @noptrix has to say about it as well.

Cheers.
